SELECT * FROM MEMBER;

UPDATE MEMBER SET AGE=25 WHERE ID='dragon';
UPDATE MEMBER SET AGE=35 WHERE ID='newlec';
INSERT INTO MEMBER(ID, PWD, NAME, AGE) VALUES('kang', 111, '강호동', 35);
DELETE FROM MEMBER WHERE PWD=333;
COMMIT;

SELECT * FROM NOTICE;

--INNER JOIN, INNER 생략 가능
SELECT * FROM MEMBER INNER JOIN NOTICE ON MEMBER.ID = NOTICE.WRITER_ID;
SELECT * FROM MEMBER JOIN NOTICE ON MEMBER.ID = NOTICE.WRITER_ID;

--OUTER JOIN
SELECT * FROM NOTICE N LEFT OUTER JOIN MEMBER M ON N.WRITER_ID = M.ID;
SELECT * FROM NOTICE N RIGHT OUTER JOIN MEMBER M ON N.WRITER_ID = M.ID;
SELECT * FROM NOTICE N FULL OUTER JOIN MEMBER M ON N.WRITER_ID = M.ID;