--7.16
CREATE TABLE MEMBER
(
    ID VARCHAR2(50),
    PWD NVARCHAR2(50),
    NAME NVARCHAR2(50),
    GENDER NCHAR(2), -- 남성 OR 여성 utf8
    AGE NUMBER(3),
    BIRTHDAY CHAR(10), -- 2020-07-15 총 10글자
    PHONE CHAR(13), -- 010-1234-1234 총 13글자
    REGDATE DATE
);

INSERT INTO MEMBER(GENDER) VALUES('남성');

SELECT LENGTHB(GENDER) FROM MEMBER; --GENDER 글자수 알아보기

DROP TABLE MEMBER;

SELECT LENGTH('ABC') FROM DUAL; -- 문자 개수 세는 방법
SELECT LENGTHB('ㅋㅋㅋ') FROM DUAL; -- 문자 바이트수 알고 싶다, 한글은 한글자당 3바이트

--7.17
ALTER TABLE MEMBER MODIFY ID NVARCHAR2(50);

ALTER TABLE MEMBER DROP COLUMN AGE;

ALTER TABLE MEMBER ADD EMAIL VARCHAR2(200);


--7.18
INSERT INTO MEMBER(ID, PWD) VALUES('gudqo1995', '1111');
INSERT INTO MEMBER(ID, PWD) VALUES('dragon', '1111');

SELECT id "USER ID", name, pwd FROM MEMBER;

UPDATE MEMBER SET PWD='333', NAME='손오공' WHERE ID = 'dragon';

INSERT INTO MEMBER(ID, PWD) VALUES('test', '1111');

DELETE MEMBER WHERE ID='test';















