CREATE SEQUENCE visit_seq
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCACHE
NOCYCLE;

CREATE TABLE VISIT (
    NO NUMBER(5,0) NOT NULL,
    WRITER VARCHAR2(21) NOT NULL,
    MEMO VARCHAR2(4000) NOT NULL,
    REGDATE DATE NOT NULL,
    CONSTRAINT VISIT_PK PRIMARY KEY (NO)
);
SELECT * FROM VISIT;