SELECT NULL + 3 FROM DUAL;

SELECT AGE + 3 FROM MEMBER;
--만약 AGE 칼럼이 NULL이면 0으로 바꿔라
SELECT NVL(AGE, 0) + 3 FROM MEMBER;
--널일경우 0으로 치환, 널이 아닐경우 AGE/10계산
SELECT NVL2(AGE, AGE/10, 0) + 3 FROM MEMBER;
--모든 HIT을 출력하되 값이 3이면 NULL값으로 출력하기
SELECT NULLIF(HIT, 3) FROM NOTICE;

--DECODE: ID가 2면 222로, 1이면 111로, 나머지는 999로 바꿔서 출력
SELECT * FROM NOTICE;
SELECT DECODE(ID,
2, 222,
1, 111,
999) FROM NOTICE;