--산술 연산자
SELECT HIT+1 HIT FROM NOTICE;
SELECT 1+'3' FROM DUAL; --DUAL: 더미테이블(의미없는 테이블)
SELECT 1||3 FROM DUAL; -- ||: 문자열 더하기
SELECT NAME||'('||ID||')' FROM MEMBER;

--비교 연산자
SELECT ID FROM NOTICE WHERE WRITER_ID = 'newlec';
SELECT * FROM NOTICE WHERE HIT>3;
SELECT * FROM NOTICE WHERE FILES IS NULL;

--관계 연산자
SELECT * FROM NOTICE WHERE HIT=12 OR HIT=13 OR HIT=14;
SELECT * FROM NOTICE WHERE HIT BETWEEN 12 AND 14;

SELECT * FROM NOTICE WHERE HIT=0 OR HIT=12;
SELECT * FROM NOTICE WHERE HIT NOT IN (0,12);

--패턴 비교 연산자
SELECT * FROM NOTICE WHERE TITLE LIKE 'JDBC%';
SELECT * FROM NOTICE WHERE TITLE LIKE '%6%';

DELETE FROM NOTICE WHERE ID BETWEEN 2 AND 6;
INSERT INTO NOTICE
VALUES(
5,
'Service 계층 추가하기',
'good',
'qqq',
SYSDATE,
23,
''
);
SELECT * FROM NOTICE WHERE TITLE LIKE 'J%';
SELECT * FROM NOTICE WHERE TITLE LIKE 'J__________';
SELECT * FROM NOTICE WHERE TITLE LIKE '%S%';

--정규식
INSERT INTO NOTICE
VALUES(
7,
'선반-접시-그릇 이 세가지요~~',
'okay',
' soso',
SYSDATE,
3,
''
);
SELECT * FROM NOTICE WHERE TITLE LIKE '%-%-%';
-- 010-2222-3333
-- 011-333-4444
-- 016-234-4353
-- 017-444-5555
-- 018-123-2345
-- 019-232-2345
-- ^01[016-9]-\d{3,4}-\d{4}$
-- \d -> [0-9]
SELECT * FROM NOTICE WHERE REGEXP_LIKE(TITLE, '01[016-9]-\d{3,4}-\d{4}');

--ROWNUM
SELECT * FROM NOTICE WHERE ROWNUM BETWEEN 1 AND 5;
SELECT * FROM NOTICE WHERE ROWNUM BETWEEN 6 AND 10; --BETWEEN첫번째 인자가 1 아니면 안됨
--ROWNUM은 원래 있던게 아니라 결과집합이 만들어 질때 생성됨
SELECT * FROM (SELECT ROWNUM NUM, NOTICE.* FROM NOTICE)
WHERE NUM BETWEEN 6 AND 10;
--괄호를 써서 먼저 결과집합을 만들고, 그리고 NUM으로 출력

COMMIT;

SELECT DISTINCT HIT FROM NOTICE;
--DISTINCT는 NUMBER만 가능한듯, 그리고 한 컬럼만 가능