SELECT SYSDATE FROM DUAL; --오라클 시간
SELECT CURRENT_DATE FROM DUAL; --사용자 시간
SELECT SYSTIMESTAMP FROM DUAL;
SELECT CURRENT_TIMESTAMP FROM DUAL;

--시간 형식 바꾸기
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';
--시간대 바꾸기
ALTER SESSION SET TIME_ZONE = '-08:00'; --LA 시간대
ALTER SESSION SET TIME_ZONE = '09:00'; --한국 시간

--날짜 추출 함수
SELECT EXTRACT(YEAR FROM SYSDATE) || '년' FROM DUAL;
SELECT EXTRACT(DAY FROM SYSDATE) FROM DUAL;
SELECT * FROM MEMBER WHERE EXTRACT(MONTH FROM REGDATE) IN(2,3,11,12);

--날짜 연산 함수
SELECT ADD_MONTHS(SYSDATE, 1) FROM DUAL;

SELECT * FROM MEMBER WHERE ADD_MONTHS(REGDATE, -6) < REGDATE;
--날짜도 비교 연산 사용 가능

--날짜 차이 알아내기
SELECT MONTHS_BETWEEN(TO_DATE('2020-04-13'), TO_DATE('2018-08-27'))
FROM DUAL;

SELECT * FROM MEMBER WHERE MONTHS_BETWEEN(SYSDATE, REGDATE) < 6;

COMMIT;