--문자열 자르기
SELECT SUBSTR('HELLO', 1, 3) FROM DUAL;
SELECT SUBSTR('HELLO', 3) FROM DUAL;
SELECT SUBSTRB(TITLE, 4) FROM NOTICE; --바이트 단위로 자름
SELECT NAME, SUBSTR(BIRTHDAY, 6, 2) MONTH FROM MEMBER;
SELECT * FROM MEMBER WHERE SUBSTR(PHONE, 1, 3)='011';
SELECT * FROM MEMBER WHERE PHONE LIKE '011%';--위에거랑 이거랑 같음
SELECT * FROM MEMBER
WHERE SUBSTR(BIRTHDAY, 6, 2) IN ('07', '08', '09')
AND PHONE IS NULL;
--문자열 합치기
SELECT CONCAT('홍', '길동') FROM DUAL;
SELECT '홍'||'길동' FROM DUAL;
--빈 공백 제거
SELECT LTRIM('     HELLO     ') FROM DUAL;
SELECT RTRIM('     HELLO     ') FROM DUAL;
SELECT TRIM('     HELLO     ') FROM DUAL;
--대소문자 변경
SELECT LOWER('PeTeRPan') FROM DUAL;
SELECT UPPER('PeTeRPan') FROM DUAL;
SELECT * FROM MEMBER WHERE UPPER(ID)='NEWLEC';
--대소문자 가리지 않고 찾기: 먼저 모든 ID 칼럼을 대문자로 바꾸고, 'NEWLEC' 찾으면 대, 소문자 다 찾아짐

--문자 바꾸기
SELECT REPLACE('WHERE WE ARE', 'WE', 'YOU') FROM DUAL; --모든 WE를 YOU로 바꾸기
SELECT TRANSLATE('WHERE WE ARE', 'WE', 'YOU') FROM DUAL;
--TRANSLATE: 모든 W는 Y로 바뀌고, 모든 E는 O로 바뀌고, U는 매칭되는게 없으니 생략
SELECT NAME, REPLACE(ADDRESS, ' ', '') FROM MEMBER;
SELECT NAME, TRANSLATE(ADDRESS, ' ', '') FROM MEMBER;