--문자열 자르기
SELECT SUBSTR('HELLO', 1, 3) FROM DUAL;
SELECT SUBSTR('HELLO', 3) FROM DUAL;
SELECT SUBSTRB(TITLE, 4) FROM NOTICE; --바이트 단위로 자름
SELECT NAME, SUBSTR(BIRTHDAY, 6, 2) MONTH FROM MEMBER;
SELECT * FROM MEMBER WHERE SUBSTR(PHONE, 1, 3)='011';
SELECT * FROM MEMBER WHERE PHONE LIKE '011%';--위에거랑 이거랑 같음
SELECT * FROM MEMBER
WHERE SUBSTR(BIRTHDAY, 6, 2) IN ('07', '08', '09')
AND PHONE IS NULL;
--문자열 합치기
SELECT CONCAT('홍', '길동') FROM DUAL;
SELECT '홍'||'길동' FROM DUAL;
--빈 공백 제거
SELECT LTRIM('     HELLO     ') FROM DUAL;
SELECT RTRIM('     HELLO     ') FROM DUAL;
SELECT TRIM('     HELLO     ') FROM DUAL;
--대소문자 변경
SELECT LOWER('PeTeRPan') FROM DUAL;
SELECT UPPER('PeTeRPan') FROM DUAL;
SELECT * FROM MEMBER WHERE UPPER(ID)='NEWLEC';
--대소문자 가리지 않고 찾기: 먼저 모든 ID 칼럼을 대문자로 바꾸고, 'NEWLEC' 찾으면 대, 소문자 다 찾아짐

--문자 바꾸기
SELECT REPLACE('WHERE WE ARE', 'WE', 'YOU') FROM DUAL; --모든 WE를 YOU로 바꾸기
SELECT TRANSLATE('WHERE WE ARE', 'WE', 'YOU') FROM DUAL;
--TRANSLATE: 모든 W는 Y로 바뀌고, 모든 E는 O로 바뀌고, U는 매칭되는게 없으니 생략
SELECT NAME, REPLACE(ADDRESS, ' ', '') FROM MEMBER;
SELECT NAME, TRANSLATE(ADDRESS, ' ', '') FROM MEMBER;

--문자열 패딩 함수
SELECT LPAD('HELLO', 10, '#') FROM DUAL;
SELECT RPAD('HELLO', 10, '#') FROM DUAL;
SELECT RPAD(NAME, 3, '_') FROM MEMBER;

--첫번째 글자 대문자로 바꾸기
SELECT INITCAP('the ...') FROM DUAL;
SELECT INITCAP('the most important thing is') FROM DUAL;

--문자열 검색 함수
SELECT INSTR('ALL WE NEED TO IS JUST TO...', 'TO') FROM DUAL;
SELECT INSTR('ALL WE NEED TO IS JUST TO...', 'TO', 15) FROM DUAL; --15번째 부터 찾기
SELECT INSTR('ALL WE NEED TO IS JUST TO...', 'TO', 1, 2) FROM DUAL; --1번 부터 2번째꺼 찾기

SELECT INSTR(PHONE, '-', 1, 2) FROM MEMBER;
SELECT INSTR(PHONE, '-', 1, 2) - INSTR(PHONE, '-', 1) -1 FROM MEMBER;

SELECT SUBSTR(PHONE, 5, INSTR(PHONE, '-', 1, 2) - INSTR(PHONE, '-', 1) -1) FROM MEMBER;

--문자열 길이 구하기
SELECT LENGTH('WHERE WE ARE') FROM DUAL;
