--도메인 제약조건
INSERT INTO notice (
    id,
    title,
    writer_id
) VALUES (
    9,
    '9번째 게시글',
    'newlec'
);

SELECT * FROM NOTICE;
COMMIT;
--CHECK 제약조건
CREATE TABLE TEST (
ID VARCHAR2(50) NULL,
PHONE VARCHAR2(200) CHECK(PHONE LIKE '010-%-____') NOT NULL,
EMAIL VARCHAR2(500) NULL
);
ALTER TABLE TEST ADD CONSTRAINT CK_TEST_PHONE
CHECK(PHONE LIKE '010-%-____');

INSERT INTO MEMBER(ID, PWD, NAME, PHONE)
VALUES('peter', '111', '피터', '010-4444-5555');
COMMIT;
--정규식 사용
ALTER TABLE MEMBER
DROP CONSTRAINT MEMBER_PHONE_CHK1;

SELECT * FROM user_constraints
WHERE TABLE_NAME='MEMBER';

ALTER TABLE MEMBER
ADD CONSTRAINT MEMBER_PHONE_CHK1
CHECK(REGEXP_LIKE(PHONE, '^01[01]-\d{3,4}-\d{4}$'));

--엔티티 제약조건 PRIMARY KEY, UNIQUE
CREATE TABLE NOTICE (
ID NUMBER CONSTRAINT NOTICE_ID_PK PRIMARY KEY, --기본키 제약 조건
TITLE VARCHAR2(300) NOT NULL, --NOT NULL
WRITER_ID VARCHAR2(50) NOT NULL UNIQUE, --NOT NULL/UNIQUE
CONTENT VARCHAR2(4000),
REGDATE DATE DEFAULT SYSDATE, --기본값 현재 날짜
HIT NUMBER DEFAULT 0 --기본값 0
);

--SEQUENCE 일련번호
INSERT INTO NOTICE(ID, TITLE, WRITER_ID)
VALUES(NOTICE_ID_SEQ.NEXTVAL, '시퀀스 예제', 'JEON');