--회원테이블 스키마
CREATE TABLE STUDENT (
    ID VARCHAR2(12) NOT NULL,
    PASS VARCHAR2(12) NOT NULL,
    NAME VARCHAR2(10) NOT NULL,
    PHONE1 VARCHAR2(3) NOT NULL,
    PHONE2 VARCHAR2(4) NOT NULL,
    PHONE3 VARCHAR2(4) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    ZIPCODE VARCHAR2(7) NOT NULL,
    ADDRESS1 VARCHAR2(120) NOT NULL,
    ADDRESS2 VARCHAR2(50) NOT NULL,
    CONSTRAINT STUDENT_PK PRIMARY KEY(ID)
);

--우편번호 스키마
CREATE TABLE ZIPCODE (
    SEQ NUMBER(5,0) NOT NULL,
    ZIPCODE VARCHAR2(7) NOT NULL,
    SIDO VARCHAR2(6) NOT NULL,
    GUGUN VARCHAR2(30),
    DONG VARCHAR2(50) NOT NULL,
    RI VARCHAR2(80),
    BUNJI VARCHAR2(20),
    CONSTRAINT ZIPCODE_PK PRIMARY KEY (SEQ)
);

SELECT * FROM STUDENT;
SELECT * FROM ZIPCODE;